context:
  version: "13.0.0"
  nanovdb_version: "32.9.0" # NanoVDB.h

recipe:
  name: openvdb-split
  version: ${{ version }}

source:
  url: https://github.com/AcademySoftwareFoundation/openvdb/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 4d6a91df5f347017496fe8d22c3dbb7c4b5d7289499d4eb4d53dd2c75bb454e1
  patches:
    - 2138.patch # https://github.com/AcademySoftwareFoundation/openvdb/pull/2138
    - 2148.patch # https://github.com/AcademySoftwareFoundation/openvdb/pull/2148

build:
  number: 3
  skip: match(python, "<3.11")

outputs:
  - staging:
      name: openvdb-build
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ stdlib("c") }}
        - cmake
        - pkg-config
        - ${{ "jemalloc" if linux }}
        - ${{ "make" if not win }}
        - if: build_platform != target_platform
          then:
            - cross-python_${{ target_platform }}
            - python
            - numpy
            - nanobind
      host:
        - blosc
        - libboost-devel
        - nanobind
        - numpy >=1.23.0
        - python
        - tbb-devel
        - ${{ "glew" if win }}
        - glfw
        - tbb-devel
        - zlib
        - if: linux
          then:
            - libgl-devel
            - libglu
        - ${{ "jemalloc" if linux }}
    build:
      script:
        env:
          # TODO: include CMAKE modules in dev
          SHARED_CMAKE_ARGS: >
            -DNANOVDB_BUILD_PYTHON_MODULE=ON
            -DNANOVDB_BUILD_TOOLS=OFF
            -DNANOVDB_BUILD_TOOLS=ON
            -DNANOVDB_USE_OPENVDB=ON
            -DNANOVDB_USE_OPENVDB=ON
            -DNANOVDB_USE_TBB=ON
            -DOPENVDB_BUILD_BINARIES=ON
            -DOPENVDB_BUILD_CORE=ON
            -DOPENVDB_BUILD_NANOVDB=ON
            -DOPENVDB_BUILD_NANOVDB=ON
            -DOPENVDB_BUILD_PYTHON_MODULE=ON
            -DOPENVDB_BUILD_VDB_LOD=ON
            -DOPENVDB_BUILD_VDB_PRINT=ON
            -DOPENVDB_BUILD_VDB_RENDER=ON
            -DOPENVDB_BUILD_VDB_TOOL=ON
            -DOPENVDB_BUILD_VDB_VIEW=ON
            -DOPENVDB_CORE_SHARED=ON
            -DOPENVDB_CORE_STATIC=OFF
            -DOPENVDB_INSTALL_CMAKE_MODULES=ON
            -DUSE_EXPLICIT_INSTANTIATION=OFF
            -Wno-dev
        content:
          - mkdir -p build
          - cd build
          - if: win
            then:
              - set CMAKE_BUILD_PARALLEL_LEVEL=%CPU_COUNT%
              - >
                cmake .. %CMAKE_ARGS% %SHARED_CMAKE_ARGS%
                -DVDB_PYTHON_INSTALL_DIRECTORY="%PREFIX%/Lib/site-packages"
                -DPython_EXECUTABLE:PATH=%PYTHON%
                -Dnanobind_DIR=%SP_DIR%/nanobind/cmake
            else:
              - export CMAKE_BUILD_PARALLEL_LEVEL=${CPU_COUNT}
              - >
                cmake .. $CMAKE_ARGS $SHARED_CMAKE_ARGS
                -DPython_EXECUTABLE:PATH=${PYTHON}
                -Dnanobind_DIR=$SP_DIR/nanobind/cmake
          - cmake --build . --target install --config Release

  - package:
      name: openvdb
    inherit: openvdb-build
    requirements:
      run:
        - numpy
        - python
      run_exports:
        - ${{ pin_subpackage('openvdb', upper_bound='x') }}
    build:
      files:
        include:
          - include/openvdb/**
          - lib/cmake/OpenVDB/**
          - if: win
            then:
              - Library/bin/openvdb*.dll
              - Lib/site-packages/openvdb*
            else:
              - lib/libopenvdb*
              - lib/python*/site-packages/openvdb*
    tests:
      - python:
          imports:
            - openvdb
          pip_check: true
      - script: >
          python -c
          "import openvdb;
          import numpy;
          grid = openvdb.FloatGrid();
          grid.copyFromArray(numpy.random.rand(200, 200, 200))"
        requirements:
          run: [numpy]
      - script:
          - if: win
            then:
              - if not exist %LIBRARY_BIN%\openvdb%SHLIB_EXT% exit 1
              - if not exist %LIBRARY_INC%\openvdb\openvdb.h exit 1
              - if not exist %LIBRARY_LIB%\cmake\OpenVDB\FindOpenVDB.cmake exit 1
            else:
              - test -f ${PREFIX}/include/openvdb/openvdb.h
              - test -f ${PREFIX}/lib/cmake/OpenVDB/FindOpenVDB.cmake
              - test -f ${PREFIX}/lib/libopenvdb$SHLIB_EXT

  - package:
      name: openvdb-tools
    inherit: openvdb-build
    requirements:
      run:
        - ${{ pin_subpackage('openvdb', upper_bound='x') }}
    build:
      files:
        include:
          - if: win
            then: Library/bin/vdb_*
            else: bin/vdb_*
    tests:
      - script:
          - vdb_print --help
          - vdb_lod --help
          - vdb_render --help
          - vdb_tool --help

  - package:
      name: nanovdb
      version: ${{ nanovdb_version }}
    inherit: openvdb-build
    requirements:
      run:
        - python
        - ${{ pin_subpackage('openvdb', upper_bound='x') }}
      run_exports:
        - ${{ pin_subpackage('nanovdb', upper_bound='x.x') }}
    build:
      files:
        include:
          - if: win
            then:
              - Library/bin/nanovdb*.dll
              - Lib/site-packages/nanovdb*
            else:
              - lib/libnanovdb*
              - lib/python*/site-packages/nanovdb*
    tests:
      - python:
          imports:
            - nanovdb
          pip_check: true
      - script:
        - if: win
          then:
            - dir %LIBRARY_BIN%\nanovdb*.dll
          else:
            - test -f ${PREFIX}/lib/libnanovdb${{ SHLIB_EXT }}

  - package:
      name: nanovdb-dev
      version: ${{ nanovdb_version }}
    inherit: openvdb-build
    requirements:
      run:
        - ${{ pin_subpackage('nanovdb', upper_bound='x.x') }}
    build:
      files:
        include:
          - include/nanovdb/**/*.{h,cuh}
          - if: win
            then:
              - Library/lib/nanovdb*.lib
            else:
                - lib/libnanovdb*.a
    tests:
      - script:
        - test -f ${PREFIX}/include/nanovdb/NanoVDB.h

  - package:
      name: nanovdb-tools
      version: ${{ nanovdb_version }}
    inherit: openvdb-build
    requirements:
      run:
        - ${{ pin_subpackage('nanovdb', upper_bound='x.x') }}
    build:
      files:
        include:
          - ${{ "Library/" if win }}bin/nanovdb_convert.exe
          - ${{ "Library/" if win }}bin/nanovdb_print.exe
          - ${{ "Library/" if win }}bin/nanovdb_validate.exe
    tests:
      - script:
          - nanovdb_convert --help
          - nanovdb_print --help
          - nanovdb_validate --help

about:
  summary: Sparse volume data structure and tools
  description: |
    Open source C++ library comprising a novel hierarchical data structure and a
    large suite of tools for the efficient storage and manipulation of sparse
    volumetric data discretized on three-dimensional grids. It was developed by
    DreamWorks Animation for use in volumetric applications typically
    encountered in feature film production.
  license: Apache-2.0
  license_file:
    - LICENSE
    - RE-LICENSE_NOTE.txt
  homepage: https://github.com/AcademySoftwareFoundation/openvdb
  repository: https://github.com/AcademySoftwareFoundation/openvdb

extra:
  recipe-maintainers:
    - versatran01
    - tetov
